### ISSUE TITLE
Ensure that /etc/hosts.deny exists

### ISSUE THREAD

**Issue by carlalexander** [debops/ansible-tcpwrappers#12]
I'm getting this error with the Xenial docker image. The `/etc/hosts.deny` doesn't exists for some reason.

```
TASK [debops.tcpwrappers : Configure access in /etc/hosts.deny] ****************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Destination /etc/hosts.deny does not exist !", "rc": 257}
```

Not sure if this something the role should handle. But could we had a step to ensure the file is present maybe?

**Comment by drybjed** [comment]
I suppose we could... Can you confirm that the `/etc/hosts.deny` file does not exist at all in this image when it's started?
